# Generated by Django 4.0.6 on 2022-08-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
