# Generated by Django 4.0.6 on 2022-08-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_review_id_by_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='id_by_book',
            new_name='book_id',
        ),
    ]
