# Generated by Django 4.0.6 on 2022-07-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name="city's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="city's name")),
            ],
        ),
    ]
