# Generated by Django 4.0.6 on 2022-07-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjanGoBookStoRe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="City's description"),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=25, verbose_name="City's name"),
        ),
    ]
