# Generated by Django 4.0.6 on 2022-07-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjanGoBookStoRe', '0003_city_post_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Region's name")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Region's description")),
            ],
        ),
    ]
