# Generated by Django 4.0.6 on 2022-07-27 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjanGoBookStoRe', '0004_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='Cities', to='DjanGoBookStoRe.region', verbose_name='Region'),
            preserve_default=False,
        ),
    ]
