# Generated by Django 4.0.6 on 2022-07-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjanGoBookStoRe', '0002_alter_city_description_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='post_index',
            field=models.IntegerField(default=123, verbose_name='Post Index'),
            preserve_default=False,
        ),
    ]
